// Projects done
export const projects = [
    {
        name: "Rotary Club of Nakasero Central",
        description: 'WordPress Rotary Website',
        link: 'https://rcnakaserocentral.com/',
        image: '@/assets/images/rc-nakasero-central.jpg',
        alt: 'rc-nakasero-central',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: "Monkey O'Clock",
        description: 'WordPress Tours & Travel Website',
        link: 'https://monkey-oclock.com/',
        image: '@/assets/images/monkey-oclock.jpg',
        alt: 'monkey-oclock',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: 'Buz Point of Sale',
        description: 'React Native Point of Sale App',
        link: 'https://play.google.com/apps/internaltest/4701657296178605696',
        image: '@/assets/images/buz-pos.png',
        alt: 'buz-pos',
        category: 'mobile-app, web-app',
        tech: ['React Native', 'React JS', 'Node.JS', 'MongoDB', 'PHP'],
    },
    {
        name: 'Ugrowth',
        description: 'WordPress News Website',
        link: 'https://ugrowth.co/',
        image: '@/assets/images/ugrowth.jpg',
        alt: 'ugrowth',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: 'ioTec Pay',
        description: 'WooCommerce Payment Gateway Extension for Airtel and MTN Mobile Money',
        link: 'https://wordpress.com/plugins/iotecpay',
        image: '@/assets/images/iotec.jpg',
        alt: 'iotec-pay',
        category: 'wp-plugin',
        tech: ['WordPress', 'PHP'],
    },
    {
        name: 'Gardenia Spa',
        description: 'Wordpress Spa Website',
        link: 'https://gardeniaspaltd.com/',
        image: '@/assets/images/gardenia-spa.png',
        alt: 'gardenia-spa',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: 'Ropani Tours',
        description: 'Wordpress Tours and Travel Website.',
        link: 'https://ropanitours.com/',
        image: '@/assets/images/ropanitours.png',
        alt: 'ropani-tours',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: 'UG Mix Maestro app',
        description: 'Android Mobile Game',
        link: '',
        image: '@/assets/images/ug-mix-maestro-2.png',
        alt: 'ug-mix-maestro',
        category: 'mobile-app',
        tech: ['Android', 'Java'],
    },
    {
        name: 'Cornerstone Community Educational Schools Buwate',
        description: 'WordPress School Website',
        link: 'https://cornerstoneug.com/',
        image: '@/assets/images/cornerstone-2.png',
        alt: 'cornerstone-community-edu',
        category: 'website',
        tech: ['WordPress', 'PHP'],
    },
    {
        name: 'Apricot Guest House',
        description: 'WordPress Hotel Website',
        link: 'https://apricotguesthouse.org/',
        image: '@/assets/images/apricot.jpg',
        alt: 'apricot-guest-house',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: 'Rotafield Schools',
        description: 'WordPress Kindergarten Website',
        link: 'https://rotafieldschools.com/',
        image: '@/assets/images/rotafield-2.png',
        alt: 'rotafield-schools',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: 'Bell Lager Shake n Win',
        description: 'Android Mobile Game',
        link: 'https://www.youtube.com/embed/nQtcRtyUGU4',
        image: '@/assets/images/bell-lager-shake-n-win.png',
        alt: 'bell-shake-n-win',
        category: 'mobile-app',
        tech: ['Android', 'Java'],
    },
    {
        name: 'Just Katogo',
        description: 'WordPress Restaurant Website',
        link: 'https://justkatogo.com/',
        image: '@/assets/images/just-katogo-2.png',
        alt: 'just-katogo',
        category: 'website',
        tech: ['WordPress'],
    },
    {
        name: "Uganda Bankers' SACCO",
        description: 'WordPress Savings and Credit Cooperative Organisation Website',
        link: 'https://ugandabankersacco.com/',
        image: '@/assets/images/ubsacco-2.png',
        alt: 'ug-bankers-sacco',
        category: 'website',
        tech: ['WordPress'],
    },
]